package com.wjx.kablade.client.renderer;

import com.wjx.kablade.Main;
import com.wjx.kablade.Entity.Render.ElectricSkillShader;
import com.wjx.kablade.SlashBlade.specialattack.RaidenCycloneTimeline;
import com.wjx.kablade.config.ModConfig;
import com.wjx.kablade.network.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.*;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.*;
import net.minecraftforge.client.event.RenderWorldLastEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.*;
import org.lwjgl.opengl.GL11;

import java.util.*;

/** 重磁暴·斩的确定性无实体世界渲染器。 */
@SideOnly(Side.CLIENT)
@Mod.EventBusSubscriber(modid=Main.MODID,value=Side.CLIENT)
public final class RaidenCycloneRenderer {
    private static final Map<Long,Fx> ACTIVE=new LinkedHashMap<Long,Fx>();private static final Map<Integer,Deque<Tip>> TIPS=new HashMap<Integer,Deque<Tip>>();private static final float TAU=(float)Math.PI*2;
    private RaidenCycloneRenderer(){}
    public static void start(MessageRaidenCycloneStart m){long start=m.startGameTime;Minecraft mc=Minecraft.getMinecraft();if(start<=0&&mc.world!=null)start=mc.world.getTotalWorldTime();ACTIVE.put(m.castId,new Fx(m,start));}
    public static void stop(long id,byte reason){Fx fx=ACTIVE.get(id);if(fx==null)return;if(reason==MessageRaidenCycloneEnd.COMPLETE)fx.fadeTick=worldTime();else ACTIVE.remove(id);}
    public static boolean isActive(int id){for(Fx f:ACTIVE.values())if(f.casterId==id)return true;return false;}
    public static void recordBladeTip(int id,Vec3d p){Deque<Tip> q=TIPS.get(id);if(q==null){q=new ArrayDeque<Tip>();TIPS.put(id,q);}q.addLast(new Tip(p,worldTime()));while(q.size()>28)q.removeFirst();}
    public static boolean hasActive(){return !ACTIVE.isEmpty();}
    public static void clear(){ACTIVE.clear();TIPS.clear();}
    public static void drawWorld(float partial){Minecraft mc=Minecraft.getMinecraft();if(mc.world==null||ACTIVE.isEmpty())return;long now=mc.world.getTotalWorldTime();Iterator<Fx> it=ACTIVE.values().iterator();while(it.hasNext()){Fx f=it.next();if(now-f.start>112||(f.fadeTick>0&&now-f.fadeTick>7)){TIPS.remove(f.casterId);it.remove();}}if(ACTIVE.isEmpty())return;float oldX=OpenGlHelper.lastBrightnessX,oldY=OpenGlHelper.lastBrightnessY;boolean pushed=false;try{GlStateManager.disableLighting();GlStateManager.disableCull();GlStateManager.disableTexture2D();GlStateManager.enableBlend();GlStateManager.depthMask(false);OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit,240,240);GlStateManager.pushMatrix();pushed=true;GlStateManager.translate(-renderX(),-renderY(),-renderZ());for(Fx f:ACTIVE.values())draw(f,partial);}finally{if(pushed)GlStateManager.popMatrix();OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit,oldX,oldY);GlStateManager.enableTexture2D();GlStateManager.depthMask(true);GlStateManager.disableBlend();GlStateManager.enableCull();GlStateManager.enableLighting();}}
    private static void draw(Fx fx,float partial){float seconds=(worldTime()+partial-fx.start)/20F;if(seconds<-.1F||seconds>5.4F)return;float global=1-smooth((seconds-4.42F)/(5.04F-4.42F));if(fx.fadeTick>0)global*=1-smooth((worldTime()+partial-fx.fadeTick)/7F);Vec3d target=target(fx,partial);int old=ElectricSkillShader.bind(seconds*20,4);BufferBuilder b=Tessellator.getInstance().getBuffer();GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA,GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA,GlStateManager.SourceFactor.ONE,GlStateManager.DestFactor.ZERO);b.begin(GL11.GL_QUADS,DefaultVertexFormats.POSITION_TEX_COLOR);ground(b,fx,target,seconds,global,false);afterimages(b,fx,target,seconds,global,false);Tessellator.getInstance().draw();GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA,GlStateManager.DestFactor.ONE,GlStateManager.SourceFactor.ONE,GlStateManager.DestFactor.ZERO);b.begin(GL11.GL_QUADS,DefaultVertexFormats.POSITION_TEX_COLOR);slashes(b,fx,target,seconds,global);ground(b,fx,target,seconds,global,true);pillar(b,fx,target,seconds,global);lightning(b,fx,target,seconds,global);impacts(b,target,seconds,global);afterimages(b,fx,target,seconds,global,true);fragments(b,fx,target,seconds,global);tipTrail(b,fx,global);Tessellator.getInstance().draw();ElectricSkillShader.restore(old);}
    private static void slashes(BufferBuilder b,Fx f,Vec3d target,float sec,float alpha){int segments=quality(6,10,14);for(RaidenCycloneTimeline.SlashSpec s:RaidenCycloneTimeline.SLASHES){float age=sec-s.start;if(age<0||age>s.life)continue;float head=smooth(age/s.write),wipe=age<=s.eraseLead?0:smooth((age-s.eraseLead)/Math.max(s.eraseEnd-s.eraseLead,.0001F)),tail=Math.max(head-s.maxSpan,wipe*head);if(head-tail<.002F)continue;float fade=1-smooth((age-s.eraseEnd)/Math.max(s.life-s.eraseEnd,.0001F)),a=alpha*fade;slashLayer(b,f,target,s,head,tail,1,s.width*1.2F,.08F,.55F,1,a*.22F,segments,0);slashLayer(b,f,target,s,head,tail,.8F,s.width*.82F,.20F,.86F,1,a*.72F,segments,0);slashLayer(b,f,target,s,head,tail,.36F,s.width*.30F,.82F,1,1,a*.98F,segments,.015F);slashLayer(b,f,target,s,head,tail,.62F,s.width*.12F,.60F,1,1,a*.82F,segments,s.width*.42F);if(s.dark)slashLayer(b,f,target,s,head,tail,.70F,s.width*1.12F,.01F,.04F,.10F,a*.72F,segments,-.08F);}}
    private static void slashLayer(BufferBuilder b,Fx f,Vec3d target,RaidenCycloneTimeline.SlashSpec s,float head,float tail,float length,float width,float r,float g,float bl,float alpha,int segments,float offset){float layerTail=Math.max(tail,head-s.maxSpan*length);for(int i=0;i<segments;i++){float q0=i/(float)segments,q1=(i+1)/(float)segments,u0=layerTail+(head-layerTail)*q0,u1=layerTail+(head-layerTail)*q1;Vec3d a0=slashPoint(f,target,s,u0,offset-width*.5F),a1=slashPoint(f,target,s,u1,offset-width*.5F),b1=slashPoint(f,target,s,u1,offset+width*.5F),b0=slashPoint(f,target,s,u0,offset+width*.5F);band(b,a0,a1,b1,b0,r,g,bl,alpha,q0,q1);}}
    private static Vec3d slashPoint(Fx f,Vec3d target,RaidenCycloneTimeline.SlashSpec s,float u,float radiusOffset){float theta=s.angle+s.direction*s.arc*u,radius=s.radius+radiusOffset;double x=Math.cos(theta)*radius,y=s.y+Math.sin(u*Math.PI)*s.lift,z=Math.sin(theta)*radius,cx=Math.cos(s.rotateX),sx=Math.sin(s.rotateX),ry=y*cx-z*sx,rz=y*sx+z*cx,cz=Math.cos(s.rotateZ),sz=Math.sin(s.rotateZ),rx=x*cz-ry*sz;ry=x*sz+ry*cz;return scene(f,target,rx+s.centerX,ry,rz+s.centerZ);}
    private static void ground(BufferBuilder b,Fx f,Vec3d target,float sec,float alpha,boolean bright){float a=RaidenCycloneTimeline.envelope(sec,.38F,.62F,4.54F)*alpha;if(a<.002F)return;for(int ring=0;ring<4;ring++){float radius=1.05F+ring*.46F+smooth(sec/1.2F)*.35F;ring(b,target.add(0,.035,0),radius,bright?.025F:.13F,bright?.30F:.015F,bright?.82F:.025F,bright?1:.08F,a*(.82F-ring*.13F));}for(int i=0;i<8;i++){double an=i*TAU/8+sec*.44;Vec3d p=target.add(Math.cos(an)*2.55,.04,Math.sin(an)*2.55);beam(b,target.add(0,.04,0),p,bright?.018F:.06F,bright?.22F:.01F,bright?.72F:.02F,bright?1:.06F,a*.45F);}}
    private static void pillar(BufferBuilder b,Fx f,Vec3d t,float sec,float alpha){float a=Math.max(RaidenCycloneTimeline.envelope(sec,2.10F,2.28F,3.24F),RaidenCycloneTimeline.envelope(sec,3.28F,3.52F,4.42F))*alpha;if(a<.002F)return;int sheets=quality(2,3,4),segments=quality(14,19,24);for(int sheet=0;sheet<sheets;sheet++){Vec3d prev=t.add(Math.cos(sheet*TAU/sheets)*1.5,0,Math.sin(sheet*TAU/sheets)*1.5);for(int i=1;i<=segments;i++){float u=i/(float)segments;double an=sheet*TAU/sheets+u*TAU*1.65+sec*.7;Vec3d p=t.add(Math.cos(an)*(1.5-u*.65),u*7.5,Math.sin(an)*(1.5-u*.65));beam(b,prev,p,.035F,.30F,.82F,1,a*(1-u*.45F));prev=p;}}}
    private static void lightning(BufferBuilder b,Fx f,Vec3d t,float sec,float alpha){float a=Math.max(RaidenCycloneTimeline.envelope(sec,2.06F,2.18F,2.44F),Math.max(RaidenCycloneTimeline.envelope(sec,2.88F,3.02F,3.25F),RaidenCycloneTimeline.envelope(sec,3.30F,3.52F,4.42F)))*alpha;int count=quality(7,10,13);for(int i=0;i<count&&a>.002F;i++){double an=i*TAU/count+sec*.25;Vec3d from=t.add(Math.cos(an)*(1+i%4),5.5+(i%3),Math.sin(an)*(1+i%4)),to=t.add(Math.cos(an+1.2)*2.4,.2+(i%4)*.5,Math.sin(an+1.2)*2.4);bolt(b,from,to,f.seed+i*89,.032F,a*(.30F+(i%4)*.15F));}}
    private static void impacts(BufferBuilder b,Vec3d t,float sec,float alpha){for(int i=0;i<RaidenCycloneTimeline.HIT_SECONDS.length;i++){float a=RaidenCycloneTimeline.gaussian(sec,RaidenCycloneTimeline.HIT_SECONDS[i],.055F)*alpha;if(a<.002F)continue;float radius=.3F+a*2.2F;Vec3d center=t.add(0,.8,0);ring(b,t.add(0,.05,0),radius,.035F,.38F,.88F,1,a);for(int ray=0;ray<10;ray++){double angle=ray*TAU/10+i*.37;Vec3d end=center.add(Math.cos(angle)*radius*1.35,Math.sin(angle*2)*radius*.24,Math.sin(angle)*radius*1.35);beam(b,center,end,.018F+(ray%2)*.009F,.70F,.98F,1,a*.72F);}}}
    private static void afterimages(BufferBuilder b,Fx f,Vec3d target,float sec,float alpha,boolean bright){float a=Math.max(RaidenCycloneTimeline.envelope(sec,.05F,.45F,1.85F),RaidenCycloneTimeline.envelope(sec,2.65F,3.28F,4.30F))*alpha;for(int i=0;i<6&&a>.002F;i++){float sample=Math.max(0,sec-(i+1)*.052F);RaidenCycloneTimeline.Pose p=RaidenCycloneTimeline.sample(sample);Vec3d feet=scene(f,target,p.x,.03,p.z),chest=feet.add(0,1.42,0),head=feet.add(0,1.92,0);float fade=(1-i/6F)*a;if(bright){beam(b,feet,chest,.065F,.30F,.82F,1,fade*.42F);beam(b,chest,head,.10F,.48F,.94F,1,fade*.34F);}else beam(b,feet,chest,.20F,.01F,.025F,.06F,fade*.28F);}}
    private static void fragments(BufferBuilder b,Fx f,Vec3d t,float sec,float alpha){float a=RaidenCycloneTimeline.envelope(sec,3.70F,4.40F,5.04F)*alpha;int count=quality(18,32,48);for(int i=0;i<count&&a>.002F;i++){double an=rand(f.seed,i)*TAU+sec*(.4+rand(f.seed,i+17));double r=.4+rand(f.seed,i+33)*5.5;Vec3d p=t.add(Math.cos(an)*r,.2+rand(f.seed,i+49)*4.3,Math.sin(an)*r);diamond(b,p,.025F+(float)rand(f.seed,i+65)*.1F,.28F,.82F,1,a*(.25F+(float)rand(f.seed,i+91)*.65F));}}
    private static void tipTrail(BufferBuilder b,Fx f,float alpha){Deque<Tip> q=TIPS.get(f.casterId);if(q==null||q.size()<2)return;Tip prev=null;int i=0;for(Tip tip:q){if(prev!=null){float fade=(i/(float)q.size())*alpha;beam(b,prev.p,tip.p,.025F,.45F,.88F,1,fade);}prev=tip;i++;}}
    private static Vec3d scene(Fx f,Vec3d t,double x,double y,double z){double c=Math.cos(f.rotation),s=Math.sin(f.rotation);return t.add(x*c-z*s,y,x*s+z*c);}
    private static Vec3d target(Fx f,float partial){Minecraft mc=Minecraft.getMinecraft();Entity e=f.targetId<0?null:mc.world.getEntityByID(f.targetId);if(e==null)return f.target;return new Vec3d(e.prevPosX+(e.posX-e.prevPosX)*partial,e.prevPosY+(e.posY-e.prevPosY)*partial+e.height*.5,e.prevPosZ+(e.posZ-e.prevPosZ)*partial);}
    public static Feedback feedback(Vec3d camera,float partial){Feedback best=null;float score=0;for(Fx f:ACTIVE.values()){float sec=(worldTime()+partial-f.start)/20F;Vec3d t=target(f,partial);float impact=0;for(float h:RaidenCycloneTimeline.HIT_SECONDS)impact=Math.max(impact,RaidenCycloneTimeline.gaussian(sec,h,.055F));float fade=1-smooth((float)((camera.distanceTo(t)-5)/43));if(impact*fade>score){score=impact*fade;best=new Feedback(sec,impact,fade,(f.seed&0xFFFF)/65535F*TAU);}}return best;}
    public static final class Feedback{public final float seconds,impact,fade,phase;Feedback(float s,float i,float f,float p){seconds=s;impact=i;fade=f;phase=p;}}
    private static void bolt(BufferBuilder b,Vec3d from,Vec3d to,long seed,float w,float a){Vec3d p=from;for(int i=1;i<=14;i++){float t=i/14F;Vec3d q=from.add(to.subtract(from).scale(t));if(i<14)q=q.add((rand(seed,i)-.5)*.5,(rand(seed,i+31)-.5)*.5,(rand(seed,i+61)-.5)*.5);beam(b,p,q,w,.30F,.78F,1,a);beam(b,p,q,w*.25F,1,1,1,a);p=q;}}
    private static void beam(BufferBuilder b,Vec3d a,Vec3d c,float w,float r,float g,float bl,float al){Vec3d d=c.subtract(a),s=new Vec3d(-d.z,0,d.x);s=s.lengthSquared()<1E-7?new Vec3d(w,0,0):s.normalize().scale(w);band(b,a.add(s),c.add(s),c.subtract(s),a.subtract(s),r,g,bl,al,0,1);}private static void cross(BufferBuilder b,Vec3d p,float w,float h,float r,float g,float bl,float a){quad(b,p.add(0,h,0),p.add(w,0,0),p.add(0,-h,0),p.add(-w,0,0),r,g,bl,a);quad(b,p.add(0,h,0),p.add(0,0,w),p.add(0,-h,0),p.add(0,0,-w),r,g,bl,a);}private static void diamond(BufferBuilder b,Vec3d p,float s,float r,float g,float bl,float a){quad(b,p.add(0,s,0),p.add(s,0,0),p.add(0,-s,0),p.add(-s,0,0),r,g,bl,a);}private static void ring(BufferBuilder b,Vec3d p,float radius,float w,float r,float g,float bl,float a){for(int i=0;i<56;i++){double a0=i*TAU/56,a1=(i+1)*TAU/56;band(b,p.add(Math.cos(a0)*(radius+w),0,Math.sin(a0)*(radius+w)),p.add(Math.cos(a1)*(radius+w),0,Math.sin(a1)*(radius+w)),p.add(Math.cos(a1)*(radius-w),0,Math.sin(a1)*(radius-w)),p.add(Math.cos(a0)*(radius-w),0,Math.sin(a0)*(radius-w)),r,g,bl,a,i/56F,(i+1)/56F);}}
    private static void band(BufferBuilder b,Vec3d left0,Vec3d left1,Vec3d right1,Vec3d right0,float r,float g,float bl,float a,float u0,float u1){Vec3d li0=lerp(left0,right0,.30),li1=lerp(left1,right1,.30),ri1=lerp(left1,right1,.70),ri0=lerp(left0,right0,.70);v(b,left0,u0,0,r,g,bl,0);v(b,left1,u1,0,r,g,bl,0);v(b,li1,u1,.30F,r,g,bl,a);v(b,li0,u0,.30F,r,g,bl,a);v(b,li0,u0,.30F,r,g,bl,a);v(b,li1,u1,.30F,r,g,bl,a);v(b,ri1,u1,.70F,r,g,bl,a);v(b,ri0,u0,.70F,r,g,bl,a);v(b,ri0,u0,.70F,r,g,bl,a);v(b,ri1,u1,.70F,r,g,bl,a);v(b,right1,u1,1,r,g,bl,0);v(b,right0,u0,1,r,g,bl,0);}
    private static void quad(BufferBuilder b,Vec3d a,Vec3d c,Vec3d d,Vec3d e,float r,float g,float bl,float al){v(b,a,0,0,r,g,bl,al);v(b,c,1,0,r,g,bl,al);v(b,d,1,1,r,g,bl,al);v(b,e,0,1,r,g,bl,al);}private static void v(BufferBuilder b,Vec3d p,float u,float v,float r,float g,float bl,float a){b.pos(p.x,p.y,p.z).tex(u,v).color(r,g,bl,a).endVertex();}
    private static Vec3d lerp(Vec3d a,Vec3d b,double t){return a.add(b.subtract(a).scale(t));}private static int quality(int low,int medium,int high){String q=ModConfig.GeneralConf.RaidenCycloneQuality;return "LOW".equals(q)?low:"MEDIUM".equals(q)?medium:high;}private static float smooth(float x){float t=MathHelper.clamp(x,0,1);return t*t*(3-2*t);}private static double rand(long s,int i){long x=s+i*0x9E3779B97F4A7C15L;x^=x>>>30;x*=0xBF58476D1CE4E5B9L;x^=x>>>27;x*=0x94D049BB133111EBL;x^=x>>>31;return(x&0xFFFFFF)/(double)0x1000000;}private static long worldTime(){return Minecraft.getMinecraft().world==null?0:Minecraft.getMinecraft().world.getTotalWorldTime();}private static double renderX(){return Minecraft.getMinecraft().getRenderManager().viewerPosX;}private static double renderY(){return Minecraft.getMinecraft().getRenderManager().viewerPosY;}private static double renderZ(){return Minecraft.getMinecraft().getRenderManager().viewerPosZ;}
    private static final class Fx{final long id,start,seed;final int casterId,targetId;final Vec3d origin,target;final float rotation;long fadeTick;Fx(MessageRaidenCycloneStart m,long start){id=m.castId;casterId=m.casterId;targetId=m.targetId;this.start=start;seed=m.seed;origin=new Vec3d(m.ox,m.oy,m.oz);target=new Vec3d(m.tx,m.ty,m.tz);rotation=m.rotation;}}
    private static final class Tip{final Vec3d p;final long tick;Tip(Vec3d p,long t){this.p=p;tick=t;}}
}
