package com.wjx.kablade.Entity.Render;

import com.wjx.kablade.Entity.EntityRaizanCleave;
import com.wjx.kablade.client.renderer.RaizanAnimation;
import com.wjx.kablade.config.ModConfig;
import mods.flammpfeil.slashblade.client.model.BladeModelManager;
import mods.flammpfeil.slashblade.client.model.obj.WavefrontObject;
import mods.flammpfeil.slashblade.util.ResourceLocationRaw;
import net.minecraft.client.renderer.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.*;
import net.minecraftforge.fml.relauncher.*;
import org.lwjgl.BufferUtils;
import org.lwjgl.opengl.GL11;
import javax.annotation.Nullable;
import java.nio.FloatBuffer;

/** 天殛之境：浮游 OBJ、能量拖尾、雷电、心形斩面与冲击层。 */
@SideOnly(Side.CLIENT)
public class RenderRaizanCleave extends Render<EntityRaizanCleave> {
    // 雷斩动画的 0.82 比例、枢轴和刀/鞘轨迹均以 1.20 的专用技能模型为基准。
    // 普通 SlashBlade 手持 OBJ 使用约 1/160 单位制，不能直接套入这里。
    private static final ResourceLocation TEX=new ResourceLocation("kablade","model/util/mei_c5_weapon/tex.png");
    private static final ResourceLocation BLOOM_TEX=new ResourceLocation("kablade","model/util/mei_c5_weapon/tex_bloom.png");
    private static final ResourceLocationRaw MODEL=new ResourceLocationRaw("kablade","model/util/mei_c5_weapon/mdl.obj");
    private static final FloatBuffer ROTATION_MATRIX=BufferUtils.createFloatBuffer(16);
    public RenderRaizanCleave(RenderManager manager){super(manager);shadowSize=0;shadowOpaque=0;}
    @Nullable protected ResourceLocation getEntityTexture(EntityRaizanCleave e){return TEX;}
    @Override public void doRender(EntityRaizanCleave e,double x,double y,double z,float yaw,float partial){float frame=e.getReferenceFrame(partial);RaizanAnimation.Animation a=RaizanAnimation.INSTANCE.get();float lx=OpenGlHelper.lastBrightnessX,ly=OpenGlHelper.lastBrightnessY;boolean pushed=false;try{GlStateManager.disableLighting();GlStateManager.disableCull();GlStateManager.enableBlend();GlStateManager.depthMask(false);OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit,240,240);GlStateManager.pushMatrix();pushed=true;GlStateManager.translate(x,y,z);GlStateManager.rotate(-e.rotationYaw,0,1,0);renderWeapon(a,"sheath","sheath",frame);renderWeapon(a,"blade","blade",frame);if(!ElectricSkillPostPipeline.enqueue(e,partial))renderEffects(e,a,frame);}finally{if(pushed)GlStateManager.popMatrix();OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit,lx,ly);GlStateManager.enableTexture2D();GlStateManager.depthMask(true);GlStateManager.disableBlend();GlStateManager.enableCull();GlStateManager.enableLighting();}super.doRender(e,x,y,z,yaw,partial);}
    static void drawQueued(EntityRaizanCleave e,double x,double y,double z,float partial){GlStateManager.pushMatrix();GlStateManager.translate(x,y,z);GlStateManager.rotate(-e.rotationYaw,0,1,0);renderEffects(e,RaizanAnimation.INSTANCE.get(),e.getReferenceFrame(partial));GlStateManager.popMatrix();}
    private void renderWeapon(RaizanAnimation.Animation a,String track,String part,float frame){RaizanAnimation.Pose p=a.sample(track,frame);RaizanAnimation.Model m=a.model;GlStateManager.pushMatrix();GlStateManager.translate(p.position.x,p.position.y,p.position.z);orient(p);GlStateManager.translate(m.pivot.x,m.pivot.y,m.pivot.z);GlStateManager.rotate((float)m.axis.z,0,0,1);GlStateManager.rotate((float)m.axis.y,0,1,0);GlStateManager.rotate((float)m.axis.x,1,0,0);GlStateManager.scale(m.scale,m.scale,m.scale);WavefrontObject model=BladeModelManager.getInstance().getModel(MODEL);bindTexture(TEX);GlStateManager.color(1,1,1,1);GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA,GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA,GlStateManager.SourceFactor.ONE,GlStateManager.DestFactor.ZERO);model.renderPart(part);float energy="blade".equals(part)?Math.max(a.layer("weapon_core",frame),a.layer("draw_trail",frame)):0;bindTexture(BLOOM_TEX);GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA,GlStateManager.DestFactor.ONE,GlStateManager.SourceFactor.ONE,GlStateManager.DestFactor.ZERO);GlStateManager.color(energy>.001F?.72F:1,energy>.001F?.25F:1,1,.85F);model.renderPart(part);GlStateManager.color(1,1,1,1);GlStateManager.popMatrix();}
    private static void orient(RaizanAnimation.Pose pose){pose.writeRotationMatrix(ROTATION_MATRIX);GL11.glMultMatrix(ROTATION_MATRIX);}
    private static void renderEffects(EntityRaizanCleave e,RaizanAnimation.Animation a,float f){Vec3d target=local(e.getTargetAnchor().subtract(e.getPositionVector()),e.rotationYaw);GlStateManager.disableTexture2D();GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA,GlStateManager.DestFactor.ONE,GlStateManager.SourceFactor.ONE,GlStateManager.DestFactor.ZERO);drawPass(e,a,f,target,0);drawPass(e,a,f,target,1);drawPass(e,a,f,target,2);drawPass(e,a,f,target,3);drawPass(e,a,f,target,5);GlStateManager.enableTexture2D();}
    private static void drawPass(EntityRaizanCleave e,RaizanAnimation.Animation a,float f,Vec3d target,int pass){int old=ElectricSkillShader.bind(f,pass);BufferBuilder b=Tessellator.getInstance().getBuffer();b.begin(GL11.GL_QUADS,DefaultVertexFormats.POSITION_TEX_COLOR);if(pass==0){weaponEnergy(b,a,f,e.getSeed());groundScar(b,a,f,target);}else if(pass==1){lightning(b,a,f,target,e.getSeed());}else if(pass==2){heart(b,a,f,target,e.getSeed());}else if(pass==3){particles(b,a,f,target,e.getSeed());}else{impacts(b,f,target);}Tessellator.getInstance().draw();ElectricSkillShader.restore(old);}
    private static void weaponEnergy(BufferBuilder b,RaizanAnimation.Animation a,float f,long seed){RaizanAnimation.Pose now=a.sample("blade",f);float alpha=Math.max(a.layer("weapon_core",f),a.layer("draw_trail",f));Vec3d axis=now.direction.normalize();beam(b,now.position.subtract(axis.scale(.15)),now.position.add(axis.scale(.72)),.055F,.24F,.75F,1,alpha);beam(b,now.position.subtract(axis.scale(.08)),now.position.add(axis.scale(.62)),.018F,.92F,1,1,alpha);int count=quality(8,13,18);for(int i=1;i<=count;i++){float pf=Math.max(0,f-i*.35F);RaizanAnimation.Pose p=a.sample("blade",pf),q=a.sample("blade",Math.min(f,pf+.35F));float fade=(1-i/(count+1F))*alpha;beam(b,p.position,q.position,.028F,.38F,.68F,1,fade);}}
    private static void groundScar(BufferBuilder b,RaizanAnimation.Animation a,float f,Vec3d t){float alpha=a.layer("ground_slash_scar",f);if(alpha<=.001F)return;float write=smooth((f-18.5F)/3.2F);Vec3d left=new Vec3d(-1,0,0);beam(b,t.add(left.scale(-7*write)).add(0,.04,0),t.add(left.scale(7*write)).add(0,.04,0),.18F,.30F,.60F,1,alpha*.72F);beam(b,t.add(left.scale(-7*write)).add(0,.06,0),t.add(left.scale(7*write)).add(0,.06,0),.035F,1,.92F,1,alpha);}
    private static void lightning(BufferBuilder b,RaizanAnimation.Animation a,float f,Vec3d t,long seed){float sky=Math.max(a.layer("sky_lightning",f),a.layer("lightning_branches",f));int skyCount=quality(5,7,9);if(sky>.001F)for(int i=0;i<skyCount;i++){Vec3d from=t.add(rand(seed,i)*6-3,5+rand(seed,i+19)*5,rand(seed,i+41)*6-3);bolt(b,from,t.add(rand(seed,i+61)*4-2,rand(seed,i+79)*2,rand(seed,i+97)*4-2),seed+i*71,.035F,sky*(.35F+(i%4)*.16F));}float cage=a.layer("ground_cage",f);int cageCount=quality(6,8,10);if(cage>.001F)for(int i=0;i<cageCount;i++){double an=i*Math.PI*2/cageCount;Vec3d p=t.add(Math.cos(an)*4.8,.05,Math.sin(an)*4.8);bolt(b,p,p.add(Math.cos(an)*-1.4,2.4+rand(seed,i)*2,Math.sin(an)*-1.4),seed+i*113,.03F,cage*.75F);}}
    private static void heart(BufferBuilder b,RaizanAnimation.Animation a,float f,Vec3d t,long seed){float alpha=a.layer("heart_slash",f);if(alpha<=.001F)alpha=smooth((f-31.2F)/2F)*(1-smooth((f-50)/8F));if(alpha<=.001F)return;float length=20*smooth((f-31.2F)/4F);layeredSlash(b,t.add(0,.35,-.16),new Vec3d(1,-.12,0),length,.78F,.92F,.12F,.42F,alpha);layeredSlash(b,t.add(0,.14,.02),new Vec3d(1,-.075,0),length*.96F,.30F,1,.30F,.82F,alpha*.62F);for(int i=0;i<5;i++){double ang=-Math.PI*.72+i*Math.PI*.36;Vec3d end=t.add(Math.cos(ang)*7,Math.sin(ang)*3.7,rand(seed,i)*1.2-.6);beam(b,t,end,.05F,.86F,.15F,.64F,alpha*.45F);}}
    private static void particles(BufferBuilder b,RaizanAnimation.Animation a,float f,Vec3d t,long seed){float alpha=Math.max(a.layer("orbit_embers",f),smooth((f-1)/4F)*(1-smooth((f-76)/18F)));int count=quality(20,36,52);for(int i=0;i<count;i++){double ang=rand(seed,i)*Math.PI*2+f*(.018+rand(seed,i+91)*.03),r=.6+rand(seed,i+31)*6.2;Vec3d p=t.add(Math.cos(ang)*r,.2+rand(seed,i+47)*4.5,Math.sin(ang)*r);diamond(b,p,.035F+(float)rand(seed,i+77)*.12F,.35F,.75F,1,alpha*(.25F+(float)rand(seed,i+121)*.65F));}}
    private static void impacts(BufferBuilder b,float f,Vec3d t){int[] hits={30,34,45,50,55,60,64,69,74};for(int h:hits){float a=gaussian(f,h,.75F);if(a>.002F){float radius=.35F+a*2.4F;ring(b,t,radius,.045F,.5F,.75F,1,a);for(int i=0;i<8;i++){double angle=i*Math.PI*.25+h*.17;Vec3d end=t.add(Math.cos(angle)*radius*1.35,Math.sin(angle)*radius*.52,Math.sin(angle*.5)*.18);beam(b,t,end,.018F+(i%2)*.009F,.72F,.94F,1,a*.72F);}}}}
    private static Vec3d local(Vec3d v,float yaw){double a=Math.toRadians(-yaw),c=Math.cos(a),s=Math.sin(a);return new Vec3d(v.x*c-v.z*s,v.y,v.x*s+v.z*c);}
    private static void bolt(BufferBuilder b,Vec3d from,Vec3d to,long seed,float width,float alpha){Vec3d p=from;for(int i=1;i<=12;i++){float t=i/12F;Vec3d q=from.add(to.subtract(from).scale(t));if(i<12)q=q.add((rand(seed,i)-.5)*.48,(rand(seed,i+31)-.5)*.48,(rand(seed,i+71)-.5)*.48);beam(b,p,q,width,.58F,.22F,1,alpha);beam(b,p,q,width*.28F,1,1,1,alpha);p=q;}}
    private static void layeredSlash(BufferBuilder b,Vec3d center,Vec3d direction,float length,float half,float r,float g,float bl,float a){if(length<=.01F)return;Vec3d axis=direction.normalize(),normal=new Vec3d(-axis.y,axis.x,0).normalize(),start=center.subtract(axis.scale(length*.5)),end=center.add(axis.scale(length*.5));slashDiamond(b,start,center,end,normal,half*1.85F,.42F,.02F,.30F,a*.16F);slashDiamond(b,start,center,end,normal,half,r,g,bl,a*.58F);slashDiamond(b,start,center,end,normal,half*.34F,1,.94F,1,a*.90F);beam(b,start,end,.03F,1,1,1,a*.95F);}
    private static void slashDiamond(BufferBuilder b,Vec3d start,Vec3d center,Vec3d end,Vec3d normal,float half,float r,float g,float bl,float a){Vec3d spread=normal.scale(half);v(b,start,0,.5F,r,g,bl,0);v(b,center.add(spread),.5F,0,r,g,bl,a);v(b,end,1,.5F,r,g,bl,0);v(b,center.subtract(spread),.5F,1,r,g,bl,a);}
    private static void beam(BufferBuilder b,Vec3d a,Vec3d c,float w,float r,float g,float bl,float al){Vec3d d=c.subtract(a),side=new Vec3d(-d.z,0,d.x);if(side.lengthSquared()<1E-6)side=new Vec3d(w,0,0);else side=side.normalize().scale(w);band(b,a.add(side),c.add(side),c.subtract(side),a.subtract(side),r,g,bl,al,0,1);}
    private static void cross(BufferBuilder b,Vec3d p,float w,float h,float r,float g,float bl,float a){quad(b,p.add(-w,-h,0),p.add(w,-h,0),p.add(w,h,0),p.add(-w,h,0),r,g,bl,a);quad(b,p.add(0,-h,-w),p.add(0,-h,w),p.add(0,h,w),p.add(0,h,-w),r,g,bl,a);}
    private static void diamond(BufferBuilder b,Vec3d p,float s,float r,float g,float bl,float a){quad(b,p.add(0,s,0),p.add(s,0,0),p.add(0,-s,0),p.add(-s,0,0),r,g,bl,a);}
    private static void ring(BufferBuilder b,Vec3d p,float radius,float width,float r,float g,float bl,float a){for(int i=0;i<48;i++){double a0=i*Math.PI*2/48,a1=(i+1)*Math.PI*2/48;band(b,p.add(Math.cos(a0)*(radius+width),.03,Math.sin(a0)*(radius+width)),p.add(Math.cos(a1)*(radius+width),.03,Math.sin(a1)*(radius+width)),p.add(Math.cos(a1)*(radius-width),.03,Math.sin(a1)*(radius-width)),p.add(Math.cos(a0)*(radius-width),.03,Math.sin(a0)*(radius-width)),r,g,bl,a,i/48F,(i+1)/48F);}}
    private static void band(BufferBuilder b,Vec3d left0,Vec3d left1,Vec3d right1,Vec3d right0,float r,float g,float bl,float a,float u0,float u1){Vec3d li0=lerp(left0,right0,.30),li1=lerp(left1,right1,.30),ri1=lerp(left1,right1,.70),ri0=lerp(left0,right0,.70);v(b,left0,u0,0,r,g,bl,0);v(b,left1,u1,0,r,g,bl,0);v(b,li1,u1,.30F,r,g,bl,a);v(b,li0,u0,.30F,r,g,bl,a);v(b,li0,u0,.30F,r,g,bl,a);v(b,li1,u1,.30F,r,g,bl,a);v(b,ri1,u1,.70F,r,g,bl,a);v(b,ri0,u0,.70F,r,g,bl,a);v(b,ri0,u0,.70F,r,g,bl,a);v(b,ri1,u1,.70F,r,g,bl,a);v(b,right1,u1,1,r,g,bl,0);v(b,right0,u0,1,r,g,bl,0);}
    private static void quad(BufferBuilder b,Vec3d p0,Vec3d p1,Vec3d p2,Vec3d p3,float r,float g,float bl,float a){v(b,p0,0,0,r,g,bl,a);v(b,p1,1,0,r,g,bl,a);v(b,p2,1,1,r,g,bl,a);v(b,p3,0,1,r,g,bl,a);}private static void v(BufferBuilder b,Vec3d p,float u,float v,float r,float g,float bl,float a){b.pos(p.x,p.y,p.z).tex(u,v).color(r,g,bl,a).endVertex();}
    private static Vec3d lerp(Vec3d a,Vec3d b,double t){return a.add(b.subtract(a).scale(t));}private static int quality(int low,int medium,int high){String q=ModConfig.GeneralConf.RaizanCleaveQuality;return "LOW".equals(q)?low:"MEDIUM".equals(q)?medium:high;}private static float smooth(float x){float t=MathHelper.clamp(x,0,1);return t*t*(3-2*t);}private static float gaussian(float x,float c,float w){float q=(x-c)/w;return(float)Math.exp(-q*q*.5);}private static double rand(long s,int i){long x=s+i*0x9E3779B97F4A7C15L;x^=x>>>30;x*=0xBF58476D1CE4E5B9L;x^=x>>>27;x*=0x94D049BB133111EBL;x^=x>>>31;return(x&0xFFFFFF)/(double)0x1000000;}
}
