# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Minecraft Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write Metadata
        run: ./gradlew writeMetadata

      - name: Build with Gradle
        run: ./gradlew build

      - name: Read Metadata
        id: metadata
        run: |
          ARTIFACT_NAME=$(cat ${GITHUB_WORKSPACE}/build/metadata.txt)
          echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: build/libs/*.jar
